version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: aurora-postgres

    environment:
      POSTGRES_DB: aurorabank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema:/docker-entrypoint-initdb.d

volumes:
  postgres_data: